# Generated by Django 4.2.6 on 2023-10-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("student", "Student")],
                default="student",
                max_length=20,
            ),
        ),
    ]
