# Generated by Django 4.2.6 on 2023-10-22 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                ("classroom_id", models.AutoField(primary_key=True, serialize=False)),
                ("classroom_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("classroom_code", models.CharField(max_length=20)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Classroom",
                "verbose_name_plural": "Classrooms",
                "ordering": ("classroom_id",),
            },
        ),
    ]
