# Generated by Django 4.2.6 on 2023-10-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
