# Generated by Django 4.2.6 on 2023-10-28 00:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classroom", "0003_alter_classroom_description"),
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("classroom", "student")},
        ),
    ]
