# Generated by Django 4.2.6 on 2023-10-30 14:02

from django.db import migrations, models
import trex.submission.models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0002_submissionfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionfile",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=trex.submission.models.get_upload_path
            ),
        ),
    ]
