# Generated by Django 4.2.6 on 2023-11-04 11:08

from django.db import migrations, models
import trex.submission.models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0003_alter_submissionfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionfile",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=trex.submission.models.get_upload_path,
            ),
        ),
    ]
